language: ruby
rvm:
  - 2.1
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
bundler_args: --without development
addons:
  # Replace repo_token (or remove this part)
  code_climate:
    repo_token: <insert-token-here>
notifications:
  email:
    recipients:
      - your-email@example.com
    on_failure: change
    on_success: change