language: ruby
rvm:
  - 2.1
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
bundler_args: --without development
addons:
  code_climate:
    repo_token: #{Rails.application.secrets.code_climate_repo_token}