# It's highly recommended to use MySQL for both development and test!
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: t00R

development:
  <<: *default
  database: base_development

test:
  <<: *default
  database: base_test